# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: POS 系統

# Your name to show in the footer
author: 呂學洲

# --- List of links in the navigation bar --- #

navbar-links:
  貢獻: pages/contribute
  程式架構: pages/structure

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/images/logo.png"

# By default, the image is cut into a circle. You can disable this behavior by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "evanlu361425@gmail.com"
  # facebook: deanattali
  github: evan361425
  # twitter: daattali
  # patreon: DeanAttali
  # youtube: c/daattali
  # medium: yourname
  # reddit: yourname
  # linkedin: daattali
  # xing: yourname
  stackoverflow: "12089368/呂學洲"
  # snapchat: deanat78
  # instagram: deanat78
  # spotify: yourname
  # telephone: +14159998888
  # steam: deanat78
  # twitch: yourname
  # yelp: yourname
  # telegram: yourname
  # calendly: yourname
  # mastodon: instance.url/@username
  # ORCID: your ORCID ID
  # google-scholar: your google scholar

# If you want to show a link to an RSS in the footer, add the site description here.
# If you don't want to show an RSS link, remove the following line.
# rss-description: This website is a virtual proof that I'm awesome

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

# navbar-img: "/assets/img/bgimage.png"
# footer-img: "/assets/img/bgimage.png"
# page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
# mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
# gtag: ""

# Fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "G-3D6N25J5ZM"

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
# cloudflare_analytics: ""

# Google Tag Manager ID
# gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
# fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Taipei"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
# paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  - scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
# url: "https://evan361425.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# baseurl: "/flutter-pos-system" # the subpath of your site, e.g. /blog

# github_username: evan361425

# owner_name: 呂學洲

# sass:
#   sass_dir: _sass
