name: possystem
description: POS system by Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

homepage: https://github.com/evan361425/flutter-pos-system

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.9.0+20900007

environment:
  flutter: ">=3.19.0 <3.20.0"
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core helper
  go_router: ^13.2.0
  provider: ^6.1.2
  intl: ^0.18.1
  collection: ^1.18.0
  firebase_core: ^2.25.5
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.6
  firebase_crashlytics: ^3.4.16
  firebase_in_app_messaging: ^0.7.4+15

  # services
  sqflite: ^2.3.2 # 24, 01-27
  sembast: ^3.6.0 # 24, 02-03
  shared_preferences: ^2.2.2 # 23, 10-10
  http: ^1.2.0 # 24, 01-16

  # google services
  googleapis: ^13.0.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # components
  table_calendar: ^3.0.9 # 24, 02-09
  syncfusion_flutter_charts: ^24.2.8
  spotlight_ant: ^1.0.6

  # image
  image: ^4.1.7 # 24, 01-10
  image_picker: ^1.0.7 # 24, 01-09
  image_cropper: ^5.0.1 # 23, 11-26
  cached_network_image: ^3.3.1 # 23, 12-31
  flutter_svg: ^2.0.10+1 # 24, 02-20

  # Make it easy to test
  file: ^7.0.0 # 23, 05-19

  # tools
  uuid: ^4.3.3 # 24, 01-11
  wakelock:
    git:
      url: https://github.com/evan361425/wakelock
      path: wakelock/
      ref: main
  characters: ^1.3.0 # 23, 02-17
  path_provider: ^2.1.2 # 24, 01-09
  url_launcher: ^6.2.5 # 24, 02-21
  flutter_native_splash: ^2.3.10 # 24, 01-28
  package_info_plus: ^5.0.1 # 23, 08-02
  visibility_detector: ^0.4.0+2 # 23, 03-09

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code style
  flutter_lints: ^3.0.1

  # mock object
  build_runner: ^2.4.8
  mockito: ^5.4.4
  sqflite_common: ^2.5.3 # logging
  sqflite_common_ffi: ^2.3.2+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
  - assets/food_placeholder.png
  - assets/google_sheet_icon.svg
  - assets/feature_request_please.gif
  - assets/google_signin_button.svg

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#5c98ff"
  fullscreen: true
  image: assets/logo.png
