# this page should not use Map, avoid misunderstanding
app: POS 系統
welcome: "您好😎，%s"
# diagram
alert_title: 再想一下！
cancel: 取消
confirm: 確認
success: 成功
failed: 失敗

# Backend List
menu: 菜單
setting: 設定
spreadsheet: 表單
analysis: 統計分析
stock: 庫存
customer: 客人資訊
