name: Deploy to Play Store

on:
  workflow_dispatch:
    # Enable manual run
    inputs:
      lane:
        description: "Fastlane lane to use (beta OR promote_to_production OR production)"
        required: true
        default: "beta"
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  check-version:
    name: Check pubspec.yaml version with tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load pubspec version
        id: pubspec
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: pubspec.yaml
          version: version

      - name: Extract tag name
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/v} | sed -e 's/-rc[0-9]*$//g')" >> $GITHUB_ENV

      - name: Extract version name
        run: echo "PUBSPEC_VERSION=$(echo '${{steps.pubspec.outputs.version}}' | sed -e 's/+[0-9]*$//g')" >> $GITHUB_ENV

      - name: Check with tag
        if: ${{ env.RELEASE_VERSION != env.PUBSPEC_VERSION }}
        run: exit 1

  fastlane-deploy:
    runs-on: ubuntu-18.04
    needs: check-version
    steps:
      # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Get flutter dependencies.
      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'beta' }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android
